development:
  adapter: sqlite3
  encoding: unicode
  database: ember_test
  pool: 5

test:
  adapter: sqlite3
  encoding: unicode
  database: ember_test_test
  pool: 5

production:
  adapter: sqlite3
  encoding: unicode
  database: ember_test_production
  pool: 5
